#!/bin/bash

# Check dependencies
if ! command -v jq &> /dev/null
then
    echo "jq could not be found. Please install it."
    exit
fi

# Initialize the project
npm init -y && npm i \
# Optional husky lint-staged \

# === Configs ===
## Typescript


## Eslint

## Prettier

## Nodemon

# === Scripts ===